plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/home/subh/Desktop/VIBE2SHIP/frontend/dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "/home/subh/Desktop/VIBE2SHIP/frontend"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]